ALTER TABLE users ADD COLUMN IF NOT EXISTS gender text;
ALTER TABLE users ADD COLUMN IF NOT EXISTS search_gender text;
ALTER TABLE users ADD COLUMN IF NOT EXISTS min_age integer DEFAULT 18;
ALTER TABLE users ADD COLUMN IF NOT EXISTS max_age integer DEFAULT 100;
